const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)];
const loader=$('#loader'),header=$('#header'),progress=$('.progress'),menu=$('.menu'),mobileNav=$('.mobile-nav');
const finish=()=>loader?.classList.add('done');addEventListener('load',()=>setTimeout(finish,450));setTimeout(finish,1800);
const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.12});
$$('.reveal').forEach(el=>io.observe(el));requestAnimationFrame(()=>$$('.hero .reveal').forEach((el,i)=>setTimeout(()=>el.classList.add('visible'),450+i*130)));
addEventListener('scroll',()=>{header?.classList.toggle('scrolled',scrollY>20);if(progress){const d=document.documentElement.scrollHeight-innerHeight;progress.style.width=(d>0?scrollY/d*100:0)+'%'}},{passive:true});
menu?.addEventListener('click',()=>{menu.classList.toggle('open');mobileNav?.classList.toggle('open');document.body.style.overflow=mobileNav?.classList.contains('open')?'hidden':''});
$$('.mobile-nav a').forEach(a=>a.addEventListener('click',()=>{menu?.classList.remove('open');mobileNav?.classList.remove('open');document.body.style.overflow=''}));
$$('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const id=a.getAttribute('href');if(id==='#')return;const t=$(id);if(t){e.preventDefault();t.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})}}));
function stars(canvas,count,speed){if(!canvas||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const c=canvas.getContext('2d');let pts=[],raf,start=performance.now();function reset(){const dpr=Math.min(devicePixelRatio||1,2);canvas.width=canvas.clientWidth*dpr;canvas.height=canvas.clientHeight*dpr;pts=Array.from({length:count},()=>({x:Math.random()*canvas.width,y:Math.random()*canvas.height,r:(.35+Math.random()*.95)*dpr,base:.12+Math.random()*.34,amp:.08+Math.random()*.22,v:(.025+Math.random()*.08)*dpr,phase:Math.random()*Math.PI*2,twinkle:2600+Math.random()*3600,spark:Math.random()>.93}))}function draw(now){c.clearRect(0,0,canvas.width,canvas.height);for(const p of pts){p.y+=p.v*speed;if(p.y>canvas.height+3)p.y=-3;const t=(now-start)/p.twinkle+p.phase;let a=p.base+Math.sin(t*Math.PI*2)*p.amp;if(p.spark)a+=Math.max(0,Math.sin(t*Math.PI*.55))*.18;a=Math.max(.06,Math.min(.78,a));c.beginPath();c.arc(p.x,p.y,p.r*(1+(a-p.base)*.12),0,Math.PI*2);c.fillStyle=`rgba(135,202,255,${a})`;c.shadowBlur=p.spark?8*devicePixelRatio:3*devicePixelRatio;c.shadowColor=`rgba(80,175,255,${a*.6})`;c.fill()}c.shadowBlur=0;raf=requestAnimationFrame(draw)}reset();raf=requestAnimationFrame(draw);addEventListener('resize',()=>{cancelAnimationFrame(raf);reset();raf=requestAnimationFrame(draw)},{passive:true})}
stars($('#stars'),95,1);stars($('#particles'),55,.32);